//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uvrp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banner
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Type { get; set; }
        public string Upload { get; set; }
        public string AltText { get; set; }
        public string Abstract { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string DateAdded { get; set; }
        public Nullable<int> PageId { get; set; }
        public Nullable<bool> IsHome { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
