//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uvrp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Directory
    {
        public int Id { get; set; }
        public string OrganizationName { get; set; }
        public string Industry { get; set; }
        public string Logo { get; set; }
        public string Website { get; set; }
        public string ContactAddress { get; set; }
        public string PhoneNumber { get; set; }
        public string PointOfContact { get; set; }
        public string EmailAddress { get; set; }
        public bool IsEmailPrivate { get; set; }
        public bool IsPhonePrivate { get; set; }
        public bool IsAddressPrivate { get; set; }
    }
}
