//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uvrp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UVRPEntities1 : DbContext
    {
        public UVRPEntities1()
            : base("name=UVRPEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<NewsEvent> NewsEvents { get; set; }
        public virtual DbSet<Partners> Partners { get; set; }
        public virtual DbSet<Contacts> Contacts { get; set; }
        public virtual DbSet<Directory> Directory { get; set; }
        public virtual DbSet<Comments> Comments { get; set; }
        public virtual DbSet<Video> Video { get; set; }
        public virtual DbSet<WorkForce> WorkForce { get; set; }
        public virtual DbSet<Posts> Posts { get; set; }
        public virtual DbSet<Page> Page { get; set; }
        public virtual DbSet<Banner> Banner { get; set; }
        public virtual DbSet<Masters> Masters { get; set; }
        public virtual DbSet<Footer> Footer { get; set; }
        public virtual DbSet<HomePageContent> HomePageContent { get; set; }
        public virtual DbSet<Template> Template { get; set; }
        public virtual DbSet<Resources> Resources { get; set; }
        public virtual DbSet<Team> Team { get; set; }
    }
}
