//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uvrp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Page
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Subtitle { get; set; }
        public string Content { get; set; }
        public string HeaderImage { get; set; }
        public string Slug { get; set; }
        public Nullable<bool> IsParent { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<bool> HasChild { get; set; }
        public Nullable<bool> IsCustom { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> priority { get; set; }
    }
}
