//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uvrp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partners
    {
        public int Id { get; set; }
        public string Logo { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string CompanyHomePage { get; set; }
    }
}
