//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uvrp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Posts
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public string Category { get; set; }
        public string PostStatus { get; set; }
        public string CreationDate { get; set; }
        public string EventStartDate { get; set; }
        public string EventEndDate { get; set; }
        public Nullable<bool> Recurring { get; set; }
        public string EventLocation { get; set; }
        public string ImageUpload { get; set; }
        public string Website { get; set; }
        public string Organization { get; set; }
        public string EventContact { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string startTime { get; set; }
        public string endTime { get; set; }
        public string DaysOfWeek { get; set; }
    }
}
